name: livekit_components
description: "Out-of-the-box flutter widgets for livekit client."
version: 1.3.0
homepage: https://github.com/livekit/components-flutter

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: 1.2.1
  livekit_client: ^2.6.0
  chat_bubbles: ^1.6.0
  collection: ^1.19.0
  flutter_background: ^1.3.0+1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  provider: ^6.1.2
  responsive_builder: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

topics:
  - webrtc
  - artificial-intelligence
  - livestream
  - conference
  - agent
